services:
  mongodb:
    image: mongo:7.0.9
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: "PartyPlanning"
    volumes:
      - mongo_data:/data/db
      - ./mongodb-init:/docker-entrypoint-initdb.d
      - ./mongod.conf:/etc/mongod.conf
    healthcheck:
      test: "mongosh --eval 'db.runCommand({ ping: 1 })' --quiet"
      interval: 2s
      timeout: 5s
      retries: 10
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  csharp-lightingagent:
    build:
      context: ./
      dockerfile: Agents/dotnet/lightingAgent/Dockerfile
    ports:
      - "6001:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 2s
      timeout: 5s
      retries: 10
    depends_on:
      mongodb:
        condition: service_healthy
      homeservice:
        condition: service_healthy
      lightservice:
        condition: service_healthy
      speakerservice:
        condition: service_healthy

  homeservice:
    build:
      context: ./
      dockerfile: PluginServices/HomeService/Dockerfile
    ports:
      - "5001:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 2s
      timeout: 5s
      retries: 10
    depends_on:
      mongodb:
        condition: service_healthy

  lightservice:
    build:
      context: ./
      dockerfile: PluginServices/LightService/Dockerfile
    ports:
      - "5002:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 2s
      timeout: 5s
      retries: 10
    depends_on:
      mongodb:
        condition: service_healthy

  speakerservice:
    build:
      context: ./
      dockerfile: PluginServices/SpeakerService/Dockerfile
    ports:
      - "5003:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 2s
      timeout: 5s
      retries: 10
    depends_on:
      mongodb:
        condition: service_healthy

  ui:
    build: ./UI
    stdin_open: true
    tty: true
    environment:
      - DEPLOY_ENV=docker
    depends_on:
      csharp-lightingagent:
        condition: service_healthy

volumes:
  mongo_data:
