services:
  mongodb:
    image: mongo:7.0.9
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: "HomeAutomation"
    volumes:
      - mongo_data:/data/db
      - ./mongodb-init:/docker-entrypoint-initdb.d
      - ./mongod.conf:/etc/mongod.conf
    healthcheck:
      test: "mongosh --eval 'db.runCommand({ ping: 1 })' --quiet"
      interval: 10s
      timeout: 10s
      retries: 6
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  csharp-lightingagent:
    build:
      context: ./
      dockerfile: Agents/dotnet/lightingAgent/Dockerfile
    ports:
      - "6001:80"
    depends_on:
      mongodb:
        condition: service_healthy

  homeautomationservice:
    build:
      context: ./
      dockerfile: PluginServices/HomeAutomationService/Dockerfile
    ports:
      - "5001:80"
    depends_on:
      mongodb:
        condition: service_healthy

  lightservice:
    build:
      context: ./
      dockerfile: PluginServices/LightService/Dockerfile
    ports:
      - "5002:80"
    depends_on:
      mongodb:
        condition: service_healthy

  speakerservice:
    build:
      context: ./
      dockerfile: PluginServices/SpeakerService/Dockerfile
    ports:
      - "5003:80"
    depends_on:
      mongodb:
        condition: service_healthy

  ui:
    build: ./UI
    stdin_open: true
    tty: true
    environment:
      - DEPLOY_ENV=docker

volumes:
  mongo_data:
