services:
  mongodb:
    image: mongo:7.0.9
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: "PartyPlanning"
    volumes:
      - mongo_data:/data/mongodb
      - ./mongodb-init:/docker-entrypoint-initdb.d
      - ./mongod.conf:/etc/mongod.conf
    healthcheck:
      test: "mongosh --eval 'db.runCommand({ ping: 1 })' --quiet"
      interval: 2s
      timeout: 5s
      retries: 10
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  weaviate:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.25.0
    ports:
    - 8080:8080
    - 50051:50051
    volumes:
    - weaviate_data:/data/weaviate
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      ENABLE_MODULES: 'text2vec-cohere,text2vec-huggingface,text2vec-palm,text2vec-openai,generative-openai,generative-cohere,generative-palm,ref2vec-centroid,reranker-cohere,qna-openai'
      CLUSTER_HOSTNAME: 'node1'

  python-lightingagent:
    build:
      context: ./
      dockerfile: Agents/python/lightingAgent/Dockerfile
    ports:
      - "6001:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 2s
      timeout: 5s
      retries: 10
    environment:
      MONGODB_URL: "mongodb://mongo:27017"
    depends_on:
      mongodb:
        condition: service_healthy
      homeservice:
        condition: service_healthy
      lightservice:
        condition: service_healthy
      speakerservice:
        condition: service_healthy

  csharp-lightingagent:
    build:
      context: ./
      dockerfile: Agents/dotnet/lightingAgent/Dockerfile
    ports:
      - "6101:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 2s
      timeout: 5s
      retries: 10
    depends_on:
      mongodb:
        condition: service_healthy
      homeservice:
        condition: service_healthy
      lightservice:
        condition: service_healthy
      speakerservice:
        condition: service_healthy

  lightservice:
    build:
      context: ./
      dockerfile: PluginServices/LightService/Dockerfile
    ports:
      - "5001:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 2s
      timeout: 5s
      retries: 10
    depends_on:
      mongodb:
        condition: service_healthy

  homeservice:
    build:
      context: ./
      dockerfile: PluginServices/HomeService/Dockerfile
    ports:
      - "5002:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 2s
      timeout: 5s
      retries: 10
    depends_on:
      mongodb:
        condition: service_healthy

  speakerservice:
    build:
      context: ./
      dockerfile: PluginServices/SpeakerService/Dockerfile
    ports:
      - "5003:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 2s
      timeout: 5s
      retries: 10
    depends_on:
      mongodb:
        condition: service_healthy

  sceneservice:
    build:
      context: ./
      dockerfile: PluginServices/SceneService/Dockerfile
    ports:
      - "5004:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 2s
      timeout: 5s
      retries: 10
    depends_on:
      mongodb:
        condition: service_healthy

  ui:
    build: ./UI
    stdin_open: true
    tty: true
    environment:
      - DEPLOY_ENV=docker
    depends_on:
      python-lightingagent:
        condition: service_healthy
      csharp-lightingagent:
        condition: service_healthy

volumes:
  weaviate_data:
  mongo_data:
